- src/Configuration.ts
- test/config.test.ts
Configuration didn't get configuration with specific branch name, but with specific key.
> fix: getConfiguration didn't return correct value

- src/ApiStage.ts
- src/StorageStack.ts
Allows the lambda role to publish to the encrypted SNS topic.
> fix: allow key access

- src/ApiStage.ts
- src/StorageStack.ts
Allows the lambda role to publish to the encrypted SNS topic.
> fix: Allow KMS access for lambda role

- src/Configuration.ts
- src/statics.ts
Required for https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/740
> feat: Allow prod webformulier account access to SNS

- .gitignore
- .projen/deps.json
- .projen/tasks.json
- .projenrc.js
- package.json
- src/app/submission/Database.ts
- src/app/submission/test/MockDatabase.ts
- src/app/submission/test/database.test.ts
- src/app/submission/test/docker-compose.yml
- yarn.lock
Allow listing entries by userId. This does a query on the dynamodb client.
TODO:
- pagination
- not running the dynamodb integration test in CI (or have it work)
> feat: Add list capability to database

- src/ApiStack.ts
- src/StorageStack.ts
- src/app/get-form-overview/getFormOverviewRequestHandler.ts
- src/app/get-form-overview/test/getSubmissionFromKeys.test.ts
- src/statics.ts
Fixes #
Joost heeft een bucket toegevoegd om naartoe te schrijven
> feat: Add download bucket for storing csv

- src/app/get-form-overview/test/getSubmissionFromKeys.test.ts
Add mock for store method, add download bucket config.
@WietekeNijmegen tests gefixt denk ik.
> fix: Fix test using new download bucket config

- src/Api.ts
- src/ApiStack.ts
- src/ApiStage.ts
- src/Configuration.ts
- test/main.test.ts
> feat: Add custom domain to API Gateway

- src/app/get-form-overview/getFormOverviewRequestHandler.ts
Changed form Overview lambda from PU2 (referendum) to DMS.
Limited retrieved fields to Timestamp, formname and reference.
Quick solution to retrieve all DMS forms submitted to present data in presentation.
> feat: DMS form overview

- src/StorageStack.ts
- src/app/submission/test/submissionHandler.test.ts
Naar development
- Added global secondary index to submission table to enable query on formName with a sortkey based on date
- Added mock to submissionhandler test
> feat: global secondary index and unittest fix

- src/app/get-form-overview/getFormOverviewRequestHandler.ts
Backup of database made
Creates global secondary index for database with primary key formName and sortkey date
> feat: global secondary index database form dev to acc

- src/StorageStack.ts
- src/app/get-form-overview/getFormOverviewRequestHandler.ts
- src/app/get-form-overview/test/formOverviewRequestHandler.test.ts
Fixes #
- Added comment in the hopes to again add global secondary index in main:        https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/blob/9915c1437bfe1d9a91093b0e6104793d14e94081/src/StorageStack.ts#L67
- proposed fixes from last PR (not blocking suggestions)
> fix: dev to acc

- src/app/listSubmissions/parsedEvent.ts
> fix: idtoken in parsedevent possibly undefined

- src/Api.ts
Adds an eventbridge rule to automatically create a csv file for expired forms.
Fixes https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1167
> feat: Add cron rule for expired form gathering

- src/app/zgw/rxMissionZgwHandler/rxmission-zgw.lambda.ts
> fix: extra comment

- src/app/submission/Submission.ts
- src/app/submission/SubmissionHandler.ts
- src/app/submission/test/submissionHandler.test.ts
- src/app/zgw/rxMissionZgwHandler/RxMissionZgwHandler.ts
- src/app/zgw/rxMissionZgwHandler/rxmission-zgw.lambda.ts
- src/app/zgw/zgwForwardingHandler/ZgwForwardingHandler.ts
- src/app/zgw/zgwForwardingHandler/zgw.lambda.ts
Fixes #
usertype added to zgw forwarders
> feat: samen met Joost userTypoe submission aan forwarders toegevoegd

- src/app/submission/Database.ts
- src/app/submission/FormNameIndexQueryBuilder.ts
- src/app/submission/test/database.test.ts
- src/app/submission/test/formNameIndexQueryBuilder.test.ts
Fixes #
Na migratie database zijn er bewust dubbele records.
Deze wijziging zorgt ervoor dat alleen submissions opgehaald worden die geen userType hebben in getSubmissionByFormName
Bijkomstigheid
Database integratietesten weer aangezet met een userType erbij.
> feat: aanpassing formoverview na migratie

- src/app/submission/SubmissionSchema.ts
- src/app/zgw/rxMissionZgwHandler/RxMissionZaak.ts
- src/app/zgw/rxMissionZgwHandler/RxMissionZgwHandler.ts
- src/app/zgw/rxMissionZgwHandler/test/zaak.test.ts
- src/app/zgw/zgwClient/ZgwClient.ts
Adds test for using RX Mission endpoints in ZGW
> feat: RX Mission zaak tests

- src/app/zgw/rxMissionZgwHandler/RxMissionZgwConfiguration.ts
- src/app/zgw/zgwClient/test/CatalogiLiveFetch.test.ts
Fixes #
https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/307
> feat: prod config added

- src/Configuration.ts
- src/app/zgw/rxMissionZgwHandler/RxMissionZgwConfiguration.ts
Fixes #
Na afstemming projectleider en functioneel beheerder BRIKS, feature flag prod aan:
https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/307
> feat: enable feature flag rxmission prod

- src/Configuration.ts
- src/app/zgw/rxMissionZgwHandler/RxMissionZgwConfiguration.ts
- src/app/zgw/zgwClient/test/CatalogiLiveFetch.test.ts
Na afstemming projectleider en functioneel beheerder BRIKS, feature flag prod aan:
https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/307
> feat: enable feature flag ZGW processing RxMission

- src/SubmissionZgwForwarder.ts
- src/app/zgw/rxMissionZgwHandler/RxMissionZgwConfiguration.ts
- src/app/zgw/rxMissionZgwHandler/RxMissionZgwHandler.ts
- src/app/zgw/rxMissionZgwHandler/rxmission-zgw.lambda.ts
> fix: remove sensitive logging

- src/app/zgw/zgwClient/ZgwHttpClient.ts
- src/migrations/micro-migratie-rxmission/GenerateConfigInterfaces.ts
- src/migrations/micro-migratie-rxmission/HandleRxMissionMigration.ts
- src/migrations/micro-migratie-rxmission/RxMissionMigratie.ts
- src/migrations/micro-migratie-rxmission/RxMissionPatchOmschrijving.ts
- src/migrations/micro-migratie-rxmission/RxMissionZaakConfig.ts
- src/migrations/micro-migratie-rxmission/generateConfigs.test.ts
> feat: migration rxmission lijst 2

- src/migrations/micro-migratie-rxmission/HandleRxMissionMigration.ts
- src/migrations/micro-migratie-rxmission/RxMissionMigratie.ts
https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/440
> feat: migration rxmission

- src/migrations/micro-migratie-rxmission/HandleRxMissionMigration.ts
- src/migrations/micro-migratie-rxmission/README.md
> docs: readme aanpassing voor lijst 2

- src/Configuration.ts
- src/SubmissionZgwForwarder.ts
- src/app/zgw/rxMissionZgwHandler/RXMissionDocument.ts
- src/app/zgw/rxMissionZgwHandler/RxMissionZgwHandler.ts
- src/app/zgw/rxMissionZgwHandler/test/documenten.integration.test.ts
- test/main.test.ts
#515 
Fixes hardcoded application/pdf for files sent to RxMission.
Takes mimetype from S3
#487 
Added alarm with criticality high to production. Low for dev and acc.
> fix: mime type uploads rxmission and alarm on lambda

- src/Api.ts
- src/UsEastStack.ts
> fix: remote params timout

- package.json
- src/app/submission/SubmissionHandler.ts
- yarn.lock
> chore: dependency updates
